import "./globals.css";
import React from "react";
import { DictionaryProps } from "@/lib/types";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/images/favicon.ico",
  },
};

interface RootLayoutProps extends React.PropsWithChildren, DictionaryProps {}

export default async function RootLayout(props: RootLayoutProps) {
  const { children, params } = props;


  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
